modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="medicalhealth"
version="1.0.0"
displayName="“Ω¡∆º±æ»"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="¿‰√Ê∞≤≈µ, TWSFTS_07007,MCreator"

[[dependencies.medicalhealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




